flygo:
  server:
    host: localhost
    port: 80
    webRoot: ''
    contextPath: ''
  banner:
    enable: true
    type: default
    text: ''
    file: ''
  static:
    enable: false
    pattern: static
    prefix: static
    cache: false
    favicon:
      enable: false
    mimes:
      txt: text/plain;charset=utf-8
      html: text/html;charset=utf-8
      js: text/javascript;charset=utf-8
      css: text/css;charset=utf-8
      json: application/json;charset=utf-8
      xml: text/xml;charset=utf-8
      bmp: image/bmp
      jpg: image/jpg
      png: image/png
      gif: image/gif
      ico: image/x-icon
  view:
    enable: false
    prefix: templates
    suffix: html
    cache: false
  template:
    enable: false
    delims:
      left: '{{'
      right: '}}'
  validate:
    code: 1
  log:
    type: stdout
    file:
      out: out.log
      err: err.log