server:
  maxHeaderSize: 102400
  timeout:
    read: 1m
    readHeader: 1m1s
    write: 2m
    idle: 1s
flygo:
  server:
    host: localhost
    port: 80
    tls:
      enable: false
      certFile: ''
      keyFile: ''
  banner:
    enable: true
    type: default
    text: ''
    file: ''
  template:
    enable: false
    cache: true
    root: ./templates
    suffix: .html
